/**
 * CinnShift@pzim-devdata — extension.js
 *
 * Graphical front-end for accent color shifting of the active
 * Cinnamon (desktop) and GTK (applications) themes.
 * Self-contained port of the cinnshift.py engine: theme cloning,
 * accent detection, HSV derivative discovery, selector-targeted
 * recoloring and live gsettings reload.
 *
 * The GUI is generated by Cinnamon from settings-schema.json
 * (System Settings -> Extensions -> CinnShift -> gear icon).
 * Toggling "APPLY NOW" executes the shift; the switch resets
 * itself right after execution, so it behaves like a button.
 *
 * Derived themes always reuse the fixed variant suffix
 * "-cinnshift_extension": repeated applications overwrite the same
 * clone instead of multiplying numbered themes, and always rebuild
 * from the ORIGINAL base theme (never from a previous clone), which
 * keeps accent detection stable across successive runs.
 *
 * SPDX-License-Identifier: MIT
 */

'use strict';

const GLib = imports.gi.GLib;
const Gio = imports.gi.Gio;
const Settings = imports.ui.settings;
const Gettext = imports.gettext;
const ByteArray = imports.byteArray;

let UUID = 'CinnShift@pzim-devdata';

function _(str) {
    return Gettext.dgettext(UUID, str);
}

// ── Configuration ──────────────────────────────────────────────────

const HOME = GLib.get_home_dir();
const THEMES_DIR = GLib.get_user_data_dir() + '/themes';
const SYSTEM_CINNAMON_THEME = '/usr/share/cinnamon/theme';
const SYSTEM_THEMES = '/usr/share/themes';

const VARIANT_SUFFIX = '-cinnshift_extension';

const GS_CINNAMON = 'org.cinnamon.theme';
const GS_GTK = 'org.cinnamon.desktop.interface';
const GS_WM = 'org.cinnamon.desktop.wm.preferences';

const NEUTRAL_HEX = [
    '#ffffff', '#fffffe', '#fefefe', '#fdfdfe', '#fafbfc', '#f7f7f7',
    '#f0f3f6', '#f2f2f2', '#f6f6fb', '#fcfcfc', '#fafafc',
    '#000000', '#282a33', '#21232b', '#32343d', '#333641', '#434655',
    '#3e4250', '#51535b', '#464750', '#424656', '#4d5265', '#2c2f39',
    '#464853', '#4a4c59', '#23242a', '#6b6d75', '#85878e', '#5b5f68',
    '#9093a2', '#a3a4a9', '#b2b3b8', '#c4c5c9', '#d3dae3', '#7c7e86',
    '#7c8088', '#898d94', '#e6e6e6', '#e0e0e0', '#e3e4e5', '#d1dae3',
    '#dae2e9', '#eaeef2', '#e1e7ed', '#edf1f4', '#d3e1eb', '#e4edf3',
    '#f6f9fb', '#575a60', '#3f4145', '#a6a6a6', '#d1d3da', '#90949e',
    '#b6b8c0', '#7a7f8b', '#777983', '#e5d6ca',
    '#888888', '#888', '#666666', '#666', '#aaaaaa', '#aaa',
    '#eeeeee', '#eee', '#cccccc', '#ccc', '#444444', '#444',
    '#222222', '#222', '#111111', '#111',
    '#fc4138', '#f04a50', '#f27835', '#f08437', '#f46067', '#d05258',
    '#f68086', '#fd8d88', '#f7ae86', '#ff4d4d', '#ee3239', '#f26267',
    '#f4797e', '#f75d37',
    '#6dcfa7',
    '#9f9792', '#7b736e', '#574f4a', '#463e39', '#342c27',
    '#be916d', '#785336', '#e3cf9c', '#b08952',
    '#83b6ec', '#337fdc', '#cfe1f5', '#7ad9f1', '#0f9ac8', '#caeaf2',
    '#8de6b1', '#29ae74', '#cef8d8', '#b5e98a', '#6ab85b', '#e6f9d7',
    '#f8e359', '#d29d09', '#f9f4e1', '#ffcb62', '#d68400', '#ffead1',
    '#ffa95a', '#ed5b00', '#ffe5c5', '#f78773', '#e62d42', '#f8d2ce',
    '#e973ab', '#e33b6a', '#fac7de', '#cb78d4', '#9945b5', '#e7c2e8',
    '#9e91e8', '#7a59ca', '#d5d2f5', '#c0bfbc', '#6e6d71', '#d8d7d3'
];
const NEUTRAL_SET = new Set(NEUTRAL_HEX);

// ── Selector mappings ──────────────────────────────────────────────

const SELECTOR_DYNAMIC = {
    'hover': [':hover'],
    'active': [':active'],
    'focus': [':focus'],
    'focus-visible': [':focus-visible'],
    'checked': [':checked'],
    'selected': [':selected'],
    'disabled': [':disabled'],
    'insensitive': [':insensitive'],
    'visited': [':visited'],
    'indeterminate': [':indeterminate'],
    'backdrop': [':backdrop'],
    'drop': [':drop('],
    'drag': [':drag']
};

const SELECTOR_STATIC = {
    'headerbar': ['headerbar'],
    'titlebar': ['.titlebar'],
    'decoration': ['decoration'],
    'wm-border': ['.window-frame'],
    'dialog': ['dialog', 'messagedialog'],
    'sidebar': ['sidebar', '.sidebar'],
    'paned': ['paned'],
    'statusbar': ['statusbar'],
    'toolbar': ['toolbar'],
    'separator': ['separator'],
    'frame': ['frame'],
    'border': ['border'],
    'infobar': ['infobar'],
    'button': ['button'],
    'entry': ['entry'],
    'switch': ['switch'],
    'checkbox': ['checkbutton'],
    'radio': ['radiobutton'],
    'slider': ['scale slider', 'slider'],
    'progress': ['progressbar'],
    'scrollbar': ['scrollbar'],
    'spinbutton': ['spinbutton'],
    'combobox': ['combobox'],
    'tabs': ['notebook tab'],
    'treeview': ['treeview'],
    'rows': ['row'],
    'link': ['link', ':link'],
    'spinner': ['spinner'],
    'tooltip': ['tooltip'],
    'popover': ['popover'],
    'menu': ['menu'],
    'notification': ['notification', '.banner'],
    'osd': ['.osd'],
    'panel': ['#panel'],
    'menu-cin': ['.menu'],
    'calendar-cin': ['calendar', 'calendar-events-main-box'],
    'menu-app': ['.menu-application-button'],
    'workspace': ['workspace-switcher'],
    'expo': ['expo'],
    'alt-tab': ['switcher-popup'],
    'desklet': ['.desklet'],
    'window-list': ['window-list'],
    'grouped-list': ['.grouped-window-list']
};

const ALL_SELECTOR_NAMES = Object.keys(SELECTOR_DYNAMIC)
    .concat(Object.keys(SELECTOR_STATIC))
    .filter(function(v, i, a) { return a.indexOf(v) === i; });

function selectorSettingKey(name) {
    // Keys absent from the schema: 'insensitive' is a disabled alias,
    // 'tooltip' got a -el suffix to avoid widget name clashes
    if (name === 'insensitive') return null;
    if (name === 'switch') return 's-switch-el';
    if (name === 'spinner') return 's-spinner-el';
    if (name === 'tooltip') return 's-tooltip-el';
    return 's-' + name;
}

// ── Color palettes ─────────────────────────────────────────────────

const PALETTES = {
    'pale':      { sat: [0.20, 0.45], val: [0.85, 1.00] },
    'vibrant':   { sat: [0.80, 1.00], val: [0.75, 0.95] },
    'neon':      { sat: [0.90, 1.00], val: [0.92, 1.00] },
    'grayscale': { sat: [0.00, 0.05], val: [0.30, 0.80] },
    'dark':      { sat: [0.55, 0.85], val: [0.30, 0.55] },
    'soft':      { sat: [0.40, 0.65], val: [0.70, 0.90] }
};

// ── Color utilities ────────────────────────────────────────────────

function hexToRgb(h) {
    h = h.replace('#', '');
    return [
        parseInt(h.substr(0, 2), 16),
        parseInt(h.substr(2, 2), 16),
        parseInt(h.substr(4, 2), 16)
    ];
}

function rgbToHex(rgb) {
    const f = function(c) { return ('0' + c.toString(16)).substr(-2); };
    return '#' + f(rgb[0]) + f(rgb[1]) + f(rgb[2]);
}

function hsvToHex(h, s, v) {
    const i = Math.floor(h * 6);
    const f = h * 6 - i;
    const p = v * (1 - s);
    const q = v * (1 - f * s);
    const t = v * (1 - (1 - f) * s);
    let r, g, b;
    switch (i % 6) {
        case 0: r = v; g = t; b = p; break;
        case 1: r = q; g = v; b = p; break;
        case 2: r = p; g = v; b = t; break;
        case 3: r = p; g = q; b = v; break;
        case 4: r = t; g = p; b = v; break;
        case 5: r = v; g = p; b = t; break;
    }
    return rgbToHex([
        Math.round(r * 255), Math.round(g * 255), Math.round(b * 255)]);
}

function hexToHsv(h) {
    const rgb = hexToRgb(h);
    const r = rgb[0] / 255, g = rgb[1] / 255, b = rgb[2] / 255;
    const max = Math.max(r, g, b), min = Math.min(r, g, b);
    const d = max - min;
    let hue = 0;
    if (d !== 0) {
        if (max === r) hue = ((g - b) / d + (g < b ? 6 : 0)) / 6;
        else if (max === g) hue = ((b - r) / d + 2) / 6;
        else hue = ((r - g) / d + 4) / 6;
    }
    const s = max === 0 ? 0 : d / max;
    return [hue, s, max];
}

function randomColor() {
    const baseHues = [0.00, 0.07, 0.11, 0.20, 0.48, 0.60, 0.78, 0.92];
    let h = baseHues[Math.floor(Math.random() * baseHues.length)];
    h = (((h + (Math.random() * 0.03 - 0.015)) % 1.0) + 1.0) % 1.0;
    const s = 0.65 + Math.random() * 0.30;
    const v = 0.75 + Math.random() * 0.25;
    return hsvToHex(h, s, v);
}

function randomColorPalette(paletteName) {
    const pal = PALETTES[paletteName];
    if (!pal) return randomColor();
    const baseHues = [0.00, 0.07, 0.11, 0.20, 0.48, 0.60, 0.78, 0.92];
    let h = baseHues[Math.floor(Math.random() * baseHues.length)];
    h = (((h + (Math.random() * 0.03 - 0.015)) % 1.0) + 1.0) % 1.0;
    const s = pal.sat[0] + Math.random() * (pal.sat[1] - pal.sat[0]);
    const v = pal.val[0] + Math.random() * (pal.val[1] - pal.val[0]);
    return hsvToHex(h, s, v);
}

function applyPalette(hexColor, paletteName) {
    const pal = PALETTES[paletteName];
    if (!pal) return hexColor;
    const hsv = hexToHsv(hexColor);
    const s = Math.min(Math.max(hsv[1], pal.sat[0]), pal.sat[1]);
    const v = Math.min(Math.max(hsv[2], pal.val[0]), pal.val[1]);
    return hsvToHex(hsv[0], s, v);
}

// ── File system helpers ────────────────────────────────────────────

function readText(path) {
    try {
        const [ok, data] = GLib.file_get_contents(path);
        if (!ok) return null;
        return ByteArray.toString(data);
    } catch (e) {
        return null;
    }
}

function writeText(path, content) {
    try {
        GLib.file_set_contents(path, ByteArray.fromString(content));
        return true;
    } catch (e) {
        return false;
    }
}

function fileExists(path) {
    return GLib.file_test(path, GLib.FileTest.EXISTS);
}

function listFilesRecursive(dirPath) {
    const out = [];
    const dir = Gio.File.new_for_path(dirPath);
    let enumerator = null;
    try {
        enumerator = dir.enumerate_children(
            'standard::name,standard::type',
            Gio.FileQueryInfoFlags.NONE, null);
    } catch (e) {
        return out;
    }
    let info;
    while ((info = enumerator.next_file(null)) !== null) {
        const child = dir.get_child(info.get_name());
        if (info.get_file_type() === Gio.FileType.DIRECTORY) {
            out.push(...listFilesRecursive(child.get_path()));
        } else {
            out.push(child.get_path());
        }
    }
    enumerator.close(null);
    return out;
}

function listSubdirs(dirPath) {
    const out = [];
    if (!fileExists(dirPath)) return out;
    const dir = Gio.File.new_for_path(dirPath);
    let enumerator = null;
    try {
        enumerator = dir.enumerate_children(
            'standard::name,standard::type',
            Gio.FileQueryInfoFlags.NONE, null);
    } catch (e) {
        return out;
    }
    let info;
    while ((info = enumerator.next_file(null)) !== null) {
        if (info.get_file_type() === Gio.FileType.DIRECTORY) {
            out.push(info.get_name());
        }
    }
    enumerator.close(null);
    return out;
}

function _removeEmptyDirs(dirPath) {
    const dir = Gio.File.new_for_path(dirPath);
    let enumerator = null;
    try {
        enumerator = dir.enumerate_children(
            'standard::name,standard::type',
            Gio.FileQueryInfoFlags.NONE, null);
    } catch (e) {
        return;
    }
    let info;
    while ((info = enumerator.next_file(null)) !== null) {
        if (info.get_file_type() === Gio.FileType.DIRECTORY) {
            const childPath = dir.get_child(info.get_name()).get_path();
            _removeEmptyDirs(childPath);
            try { GLib.rmdir(childPath); } catch (e) {}
        }
    }
    enumerator.close(null);
}

function deleteTree(path) {
    if (!fileExists(path)) return;
    try {
        const dir = Gio.File.new_for_path(path);
        if (dir.query_file_type(Gio.FileQueryInfoFlags.NONE, null) ===
                Gio.FileType.DIRECTORY) {
            const children = listFilesRecursive(path);
            for (const p of children) GLib.unlink(p);
            _removeEmptyDirs(path);
        } else {
            GLib.unlink(path);
            return;
        }
    } catch (e) {
        return;
    }
    try { GLib.rmdir(path); } catch (e) {}
}

function copyTree(srcPath, dstPath) {
    GLib.mkdir_with_parents(dstPath, 493); // 0o755
    const files = listFilesRecursive(srcPath);
    for (const p of files) {
        const rel = p.substring(srcPath.length + 1);
        const dstFile = dstPath + '/' + rel;
        const dstParent = dstFile.substring(0, dstFile.lastIndexOf('/'));
        GLib.mkdir_with_parents(dstParent, 493);
        try {
            const [ok, data] = GLib.file_get_contents(p);
            if (ok) GLib.file_set_contents(dstFile, data);
        } catch (e) {
            // Skip unreadable file
        }
    }
}

// ── Theme naming ───────────────────────────────────────────────────

function stripTrailingSuffix(name) {
    while (name.endsWith(VARIANT_SUFFIX)) {
        const stripped = name.slice(0, -VARIANT_SUFFIX.length);
        if (stripped.length === 0) break;
        name = stripped;
    }
    while (name.endsWith('-custom')) {
        const stripped = name.slice(0, '-custom'.length);
        if (stripped.length === 0) break;
        name = stripped;
    }
    let m = name.match(/^(.+)-(\d+)$/);
    while (m) {
        name = m[1];
        m = name.match(/^(.+)-(\d+)$/);
    }
    return name;
}

function themeNameExists(name) {
    return fileExists(THEMES_DIR + '/' + name) ||
           fileExists(SYSTEM_THEMES + '/' + name) ||
           (name === 'cinnamon' && fileExists(SYSTEM_CINNAMON_THEME));
}

// Strip ONE variant token (-cinnshift_extension, -custom, -random
// or -NUMBER) from the right end. Order irrelevant: the caller
// loops until no token remains. Returns null when nothing strips.
function _stripOneVariantToken(name) {
    const suffixes = [VARIANT_SUFFIX, '-custom', '-random'];
    for (const suf of suffixes) {
        if (name.endsWith(suf) && name.length > suf.length) {
            return name.slice(0, name.length - suf.length);
        }
    }
    const m = name.match(/^(.+)-(\d+)$/);
    if (m) return m[1];
    return null;
}

// Deep reduction: strip every variant token regardless of stacking
// order (-random-cinnshift_extension, -2-cinnshift_extension,
// -custom-random-3, ...). Missing intermediate levels are skipped;
// the result is the DEEPEST ancestor that exists on disk. Falls
// back to the input name when nothing exists below it.
function resolveOriginalTheme(name) {
    let current = name;
    let best = themeNameExists(current) ? current : null;
    while (true) {
        const stripped = _stripOneVariantToken(current);
        if (stripped === null) break;
        current = stripped;
        if (themeNameExists(current)) best = current;
    }
    return best !== null ? best : name;
}

// ── Accent detection and derivative discovery ──────────────────────

function detectAccentColor(themeDir) {
    const cssFiles = listFilesRecursive(themeDir)
        .filter(p => p.endsWith('.css'));
    if (cssFiles.length === 0) return null;

    const patterns = [
        /@define-color\s+selected_bg_color\s+(#[0-9a-fA-F]{6})/,
        /@define-color\s+theme_selected_bg_color\s+(#[0-9a-fA-F]{6})/,
        /@define-color\s+accent_bg_color\s+(#[0-9a-fA-F]{6})/,
        /@define-color\s+window_focus_border_color\s+(#[0-9a-fA-F]{6})/
    ];

    for (const css of cssFiles) {
        const content = readText(css);
        if (content === null) continue;
        for (const pat of patterns) {
            const m = pat.exec(content);
            if (m) return m[1].toLowerCase();
        }
    }

    const counter = {};
    const hexRe = /#([0-9a-fA-F]{6})\b/g;
    for (const css of cssFiles) {
        const content = readText(css);
        if (content === null) continue;
        let m;
        while ((m = hexRe.exec(content)) !== null) {
            const color = '#' + m[1].toLowerCase();
            if (NEUTRAL_SET.has(color)) continue;
            if (hexToHsv(color)[1] < 0.15) continue;
            counter[color] = (counter[color] || 0) + 1;
        }
    }
    let best = null, bestCount = 0;
    for (const color in counter) {
        if (counter[color] > bestCount) {
            best = color;
            bestCount = counter[color];
        }
    }
    return best;
}

function isDerivative(hsv, accH, hueTolerance, minV, maxV) {
    const h = hsv[0], s = hsv[1], v = hsv[2];
    if (v < minV || v > maxV) return false;
    if (s < 0.10) return false;
    let dh = Math.abs(h - accH);
    if (dh > 0.5) dh = 1.0 - dh;
    if (dh > hueTolerance) return false;
    if (s > 0.20) return true;
    if (s > 0.10 && v > 0.80) return true;
    return false;
}

function discoverDerivatives(themeDir, accentHex) {
    const accH = hexToHsv(accentHex)[0];
    const found = new Set([accentHex.toLowerCase()]);
    const files = listFilesRecursive(themeDir).filter(p =>
        p.endsWith('.css') || p.endsWith('.svg'));
    const hexRe = /#([0-9a-fA-F]{6})\b/g;
    for (const f of files) {
        const content = readText(f);
        if (content === null) continue;
        let m;
        while ((m = hexRe.exec(content)) !== null) {
            const color = '#' + m[1].toLowerCase();
            if (NEUTRAL_SET.has(color) || found.has(color)) continue;
            if (isDerivative(hexToHsv(color), accH, 0.08, 0.2, 0.99)) {
                found.add(color);
            }
        }
    }
    return found;
}

// ── Replacement engine ──────────────────────────────────────────────

function buildReplacements(sourceColors, sourceAccent, targetAccent) {
    const tHsv = hexToHsv(targetAccent.toLowerCase());
    const sHsv = hexToHsv(sourceAccent.toLowerCase());
    const tH = tHsv[0], tS = tHsv[1], tV = tHsv[2];
    const sS = sHsv[1], sV = sHsv[2];

    const hexRepl = {};
    const rgbaList = [];

    for (const scOriginal of sourceColors) {
        const sc = scOriginal.toLowerCase();
        const dHsv = hexToHsv(sc);
        const ratioS = sS > 0.01 ? dHsv[1] / sS : 1.0;
        const ratioV = sV > 0.01 ? dHsv[2] / sV : 1.0;
        const newS = Math.min(Math.max(ratioS * tS, 0.0), 1.0);
        const newV = Math.min(Math.max(ratioV * tV, 0.0), 1.0);
        const tc = hsvToHex(tH, newS, newV);

        hexRepl[sc] = tc;
        hexRepl[sc.toUpperCase()] = tc.toUpperCase();

        const srcRgb = hexToRgb(sc);
        const tgtRgb = hexToRgb(tc);
        rgbaList.push([
            srcRgb[0], srcRgb[1], srcRgb[2],
            tgtRgb[0], tgtRgb[1], tgtRgb[2]]);
    }
    return [hexRepl, rgbaList];
}

function replaceInText(content, hexRepl, rgbaList) {
    const keys = Object.keys(hexRepl)
        .sort((a, b) => b.length - a.length);
    for (const old of keys) {
        content = content.split(old).join(hexRepl[old]);
    }
    for (const r of rgbaList) {
        const re = new RegExp(
            'rgba\\(\\s*' + r[0] + '\\s*,\\s*' + r[1] +
            '\\s*,\\s*' + r[2] + '\\s*,', 'g');
        content = content.replace(
            re, 'rgba(' + r[3] + ', ' + r[4] + ', ' + r[5] + ',');
    }
    return content;
}

function processFileIfChanged(path, hexRepl, rgbaList) {
    const content = readText(path);
    if (content === null) return false;
    const newContent = replaceInText(content, hexRepl, rgbaList);
    if (newContent !== content) {
        writeText(path, newContent);
        return true;
    }
    return false;
}

// ── Selector-targeted replacement ─────────────────────────────────

function parseSelectorName(name) {
    if (name in SELECTOR_DYNAMIC) {
        return {
            dyn: SELECTOR_DYNAMIC[name].slice(),
            stat: []
        };
    }
    if (name in SELECTOR_STATIC) {
        return {
            dyn: [],
            stat: SELECTOR_STATIC[name].slice()
        };
    }
    return null;
}

function blockMatches(selectorText, dynPats, statPats) {
    const lower = selectorText.toLowerCase();
    let hasFilter = false;
    if (dynPats.length > 0) {
        hasFilter = true;
        let ok = false;
        for (const d of dynPats) {
            if (lower.indexOf(d.toLowerCase()) !== -1) { ok = true; break; }
        }
        if (!ok) return false;
    }
    if (statPats.length > 0) {
        hasFilter = true;
        let ok = false;
        for (const s of statPats) {
            if (lower.indexOf(s.toLowerCase()) !== -1) { ok = true; break; }
        }
        if (!ok) return false;
    }
    return hasFilter;
}

function processSelectorsInFile(path, selectorSpecs, targetHex,
                                 replacedKeys) {
    const content = readText(path);
    if (content === null) return { modified: false, count: 0 };

    const replacedSet = new Set(
        Object.keys(replacedKeys)
            .filter(k => k.startsWith('#') && k.length === 7)
            .map(k => k.toLowerCase()));

    let modified = false;
    let subCount = 0;
    const blockRe = /([^{}]+)\{([^{}]*)\}/g;

    const newContent = content.replace(
        blockRe,
        function(full, selText, body) {
            let matched = false;
            for (const spec of selectorSpecs) {
                if (blockMatches(selText, spec.dyn, spec.stat)) {
                    matched = true;
                    break;
                }
            }
            if (!matched) return full;

            let newBody = body;
            let changed = false;
            const lower = targetHex.toLowerCase();

            const hexRe = /#([0-9a-fA-F]{6})\b/g;
            let m;
            while ((m = hexRe.exec(body)) !== null) {
                const color = '#' + m[1].toLowerCase();
                if (replacedSet.has(color)) continue;
                newBody = newBody.split(m[0]).join(lower);
                changed = true;
                subCount++;
            }

            const rgbaRe = /rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?/g;
            while ((m = rgbaRe.exec(body)) !== null) {
                const origHex = rgbToHex([
                    parseInt(m[1]), parseInt(m[2]), parseInt(m[3])]);
                if (replacedSet.has(origHex)) continue;
                const tgtRgb = hexToRgb(lower);
                const newTriplet =
                    'rgba(' + tgtRgb[0] + ', ' + tgtRgb[1] +
                    ', ' + tgtRgb[2] + ',';
                newBody = newBody.split(m[0]).join(newTriplet);
                changed = true;
                subCount++;
            }

            if (!changed) return full;
            modified = true;
            return selText + '{' + newBody + '}';
        });

    if (modified) writeText(path, newContent);
    return { modified: modified, count: subCount };
}

// ── Theme sourcing, cloning and pipeline ───────────────────────────

function resolveThemeSource(name) {
    const local = THEMES_DIR + '/' + name;
    if (fileExists(local)) {
        return { dir: local, cleanup: null };
    }
    const system = SYSTEM_THEMES + '/' + name;
    if (fileExists(system)) {
        return { dir: system, cleanup: null };
    }
    if (name === 'cinnamon' && fileExists(SYSTEM_CINNAMON_THEME)) {
        const staging = THEMES_DIR + '/_staging_' + name;
        deleteTree(staging);
        GLib.mkdir_with_parents(staging, 493);
        copyTree(SYSTEM_CINNAMON_THEME, staging + '/cinnamon');
        writeText(
            staging + '/index.theme',
            '[X-Cinnamon]\nName=cinnamon\nType=X-Cinnamon-Theme\n');
        return { dir: staging, cleanup: staging };
    }
    return null;
}

function cloneTheme(sourceDir, targetName) {
    const targetDir = THEMES_DIR + '/' + targetName;
    GLib.mkdir_with_parents(THEMES_DIR, 493);
    deleteTree(targetDir);
    copyTree(sourceDir, targetDir);

    const idx = targetDir + '/index.theme';
    if (fileExists(idx)) {
        let c = readText(idx);
        if (c !== null) {
            c = c.replace(/^Name\s*=.*$/gm, 'Name=' + targetName);
            writeText(idx, c);
        }
    }
    const meta = targetDir + '/metadata.json';
    if (fileExists(meta)) {
        let c = readText(meta);
        if (c !== null) {
            c = c.replace(
                /"name"\s*:\s*"[^"]*"/, '"name": "' + targetName + '"');
            writeText(meta, c);
        }
    }
    return targetDir;
}

function shiftOneTheme(sourceName, cfg) {
    const result = { ok: false, name: null, message: '' };

    const src = resolveThemeSource(sourceName);
    if (src === null) {
        result.message = _('Theme not found: ') + sourceName;
        return result;
    }

    try {
        const accent = detectAccentColor(src.dir);
        if (!accent) {
            result.message =
                _('Accent color not detected for ') + sourceName;
            return result;
        }

        let targetAccent = cfg.targetAccent;
        if (targetAccent === null && cfg.palette !== null) {
            targetAccent = applyPalette(accent, cfg.palette);
        }

        if (targetAccent !== null &&
                !/^#[0-9a-fA-F]{6}$/.test(targetAccent)) {
            global.logError('[CinnShift] invalid target accent: ' +
                targetAccent);
            targetAccent = null;
        }

        const targetName = stripTrailingSuffix(sourceName) + VARIANT_SUFFIX;
        const hasColor = targetAccent !== null;
        const hasSelectors = cfg.selectorSpecs.length > 0;

        // Mode 'none' always rebuilds the clone from the resolved
        // original, even without color and without selectors: this
        // restores the original accent after CLI-generated variants.
        if (!hasColor && !hasSelectors && cfg.mode !== 'none') {
            result.message = _('Nothing to do (no color, no selector)');
            return result;
        }

        const targetDir = cloneTheme(src.dir, targetName);

        let hexRepl = {};
        let rgbaList = [];
        let modifiedCount = 0;
        let selCount = 0;

        if (hasColor) {
            const derivatives = discoverDerivatives(src.dir, accent);
            const built = buildReplacements(
                derivatives, accent, targetAccent);
            hexRepl = built[0];
            rgbaList = built[1];

            const files = listFilesRecursive(targetDir).filter(p =>
                p.endsWith('.css') || p.endsWith('.svg') ||
                p.endsWith('.rc') || p.endsWith('/gtkrc') ||
                p.endsWith('.theme') || p.endsWith('/metadata.json'));
            for (const f of files) {
                if (processFileIfChanged(f, hexRepl, rgbaList)) {
                    modifiedCount++;
                }
            }
        }

        if (hasSelectors) {
            const selTarget = hasColor ? targetAccent : accent;
            const cssFiles = listFilesRecursive(targetDir)
                .filter(p => p.endsWith('.css'));
            for (const f of cssFiles) {
                const r = processSelectorsInFile(
                    f, cfg.selectorSpecs, selTarget, hexRepl);
                if (r.modified) {
                    modifiedCount++;
                    selCount += r.count;
                }
            }
        }

        result.ok = true;
        result.name = targetName;
        result.accent = targetAccent !== null ? targetAccent : accent;
        result.message = modifiedCount + _(' file(s), ') +
                         selCount + _(' selector sub(s)');
        return result;
    } finally {
        if (src.cleanup !== null) deleteTree(src.cleanup);
    }
}

// ── gsettings and live reload ──────────────────────────────────────

let _gsCin = null;
let _gsGtk = null;
let _gsWm = null;
let _refreshTimer = 0;

function initSettingsObjects() {
    _gsCin = new Gio.Settings({ schema_id: GS_CINNAMON });
    _gsGtk = new Gio.Settings({ schema_id: GS_GTK });
    _gsWm = new Gio.Settings({ schema_id: GS_WM });
}

function refreshThemes(deskName, appName, wmName) {
    if (_refreshTimer !== 0) {
        GLib.source_remove(_refreshTimer);
        _refreshTimer = 0;
    }

    // Deterministic toggle: switch to the ORIGINAL base themes, wait,
    // then switch back to the suffixed clones. The base theme is always
    // a valid, complete theme, so no random alternate can produce an
    // unknown or broken theme anymore.
    const deskBase = stripTrailingSuffix(deskName);
    const appBase = stripTrailingSuffix(appName);
    const wmBase = stripTrailingSuffix(wmName);

    _gsCin.set_string('name', deskBase);
    _gsGtk.set_string('gtk-theme', appBase);
    _gsWm.set_string('theme', wmBase);

    _refreshTimer = GLib.timeout_add(
        GLib.PRIORITY_DEFAULT, 600, function() {
            _refreshTimer = 0;
            _gsCin.set_string('name', deskName);
            _gsGtk.set_string('gtk-theme', appName);
            _gsWm.set_string('theme', wmName);
            return GLib.SOURCE_REMOVE;
        });
}

// ── Notifications ──────────────────────────────────────────────────

function notifyResult(text) {
    try {
        GLib.spawn_async(
            null,
            ['notify-send', '-t', '120000',
             '-i', 'applications-graphics', 'CinnShift', String(text)],
            null,
            GLib.SpawnFlags.SEARCH_PATH,
            null);
    } catch (e) {
        global.log('[CinnShift] ' + text);
    }
}

// ── Extension lifecycle ────────────────────────────────────────────

let _extSettings = null;
let _applyTimer = 0;
let _busy = false;
let _lastCustomCss = null;
let _lastAccentHex = null;

function _scheduleApply() {
    if (_applyTimer !== 0) {
        GLib.source_remove(_applyTimer);
        _applyTimer = 0;
    }
    _applyTimer = GLib.timeout_add(
        GLib.PRIORITY_DEFAULT, 400, function() {
            _applyTimer = 0;
            if (_busy) return GLib.SOURCE_REMOVE;
            _busy = true;
            try {
                _runShift(_collectShiftConfig());
            } finally {
                _busy = false;
            }
            return GLib.SOURCE_REMOVE;
        });
}

function _onCustomCssChanged() {
    const v = String(_extSettings.getValue('custom-css') || '');
    // Trigger only when the user terminates an entry with a
    // separator, or clears the field: continuous typing must not
    // rebuild the theme clones on every keystroke.
    const terminated = /[,;]\s*$/.test(v);
    const cleared = _lastCustomCss !== null && v.length === 0;
    if (terminated || cleared) _scheduleApply();
    _lastCustomCss = v;
}

function _onAccentHexChanged() {
    const v = String(_extSettings.getValue('accent-hex') || '').trim();
    // Fire only on a complete valid code, or when the field is
    // cleared (falling back to the color chooser).
    const complete = /^#[0-9a-fA-F]{6}$/.test(v);
    const cleared = _lastAccentHex !== null && v.length === 0;
    if (complete || cleared) _scheduleApply();
    _lastAccentHex = v;
}

function init(metadata) {
    // Use the actual UUID (devtest- prefixed during test-spice runs)
    if (metadata && metadata.uuid) UUID = metadata.uuid;
}

function enable() {
    initSettingsObjects();
    _extSettings = new Settings.ExtensionSettings(this, UUID);
    _lastCustomCss = String(_extSettings.getValue('custom-css') || '');
    _lastAccentHex = String(_extSettings.getValue('accent-hex') || '');

    const watched = ['color-mode', 'accent-color', 'palette']
        .concat(ALL_SELECTOR_NAMES
            .map(selectorSettingKey)
            .filter(function(k) { return k !== null; }));
    for (const key of watched) {
        _extSettings.bindProperty(
            Settings.BindingDirection.IN,
            key, key.replace(/-/g, '_'),
            function() { _scheduleApply(); }, null);
    }

    // Dedicated callback for the custom selectors entry: the trigger
    // is conditional (separator typed or field cleared).
    _extSettings.bindProperty(
        Settings.BindingDirection.IN,
        'custom-css', 'custom_css_field',
        function() { _onCustomCssChanged(); }, null);

    // Dedicated callback for the manual hex entry: fires only when a
    // complete valid code is typed, never during partial typing.
    _extSettings.bindProperty(
        Settings.BindingDirection.IN,
        'accent-hex', 'accent_hex_field',
        function() { _onAccentHexChanged(); }, null);

    global.log('[CinnShift] enabled');
}

function disable() {
    if (_applyTimer !== 0) {
        GLib.source_remove(_applyTimer);
        _applyTimer = 0;
    }
    _extSettings = null;
}

// ── Settings value helpers ────────────────────────────────────────

function paletteRawToName(v) {
    if (v === null || v === undefined) return 'none';
    const s = String(v).toLowerCase();
    return ['none', 'pale', 'vibrant', 'neon', 'grayscale', 'dark', 'soft']
        .indexOf(s) !== -1 ? s : 'none';
}

function parseStoredColor(stored) {
    const s = String(stored).trim();
    const hexM = /^#[0-9a-fA-F]{6}$/.exec(s);
    if (hexM) return s.toLowerCase();
    const rgbM = /rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/.exec(s);
    if (rgbM) {
        const f = function(x) {
            return ('0' + parseInt(x).toString(16)).slice(-2);
        };
        return '#' + f(rgbM[1]) + f(rgbM[2]) + f(rgbM[3]);
    }
    return null;
}

// ── Apply flow ─────────────────────────────────────────────────────

function _collectShiftConfig() {
    const paletteName =
        paletteRawToName(_extSettings.getValue('palette'));
    const palette = paletteName === 'none' ? null : paletteName;
    const mode = String(_extSettings.getValue('color-mode') || 'none');

    let targetAccent = null;
    if (mode === 'random') {
        targetAccent = palette !== null ?
            randomColorPalette(palette) : randomColor();
    } else if (mode === 'manual') {
        // Manual hex entry wins over the color chooser when valid
        const rawHex = String(
            _extSettings.getValue('accent-hex') || '').trim();
        if (/^#[0-9a-fA-F]{6}$/.test(rawHex)) {
            targetAccent = rawHex.toLowerCase();
        } else {
            targetAccent = parseStoredColor(
                String(_extSettings.getValue('accent-color') || ''));
        }
        if (targetAccent !== null && palette !== null) {
            targetAccent = applyPalette(targetAccent, palette);
        }
    }
    // mode 'none': accent preserved, selectors still applied

    const selectorSpecs = [];
    for (const name of ALL_SELECTOR_NAMES) {
        const key = selectorSettingKey(name);
        if (key === null) continue;   // unmapped selector: skip
        let on = false;
        try {
            on = _extSettings.getValue(key);
        } catch (e) {}
        if (on) {
            const spec = parseSelectorName(name);
            if (spec !== null) selectorSpecs.push(spec);
        }
    }

    // Custom CSS selectors: free-text, comma or semicolon separated
    const rawCss = String(_extSettings.getValue('custom-css') || '');
    const fragments = rawCss.split(/[,;]/)
        .map(function(s) { return s.trim(); })
        .filter(function(s) { return s.length > 0; });
    for (const frag of fragments) {
        selectorSpecs.push({ dyn: [], stat: [frag] });
    }

    return {
        mode: mode,
        targetAccent: targetAccent,
        palette: palette,
        selectorSpecs: selectorSpecs
    };
}

function _runShift(cfg) {
    // Guard: nothing to do (no color, no selector): keep themes as-is.
    // Mode 'none' is exempted: switching to 'none' must always rebuild
    // the clone from the resolved ORIGINAL theme (see base selection
    // below), restoring the original accent after CLI variants.
    if (cfg.mode !== 'none' &&
        cfg.targetAccent === null &&
        cfg.selectorSpecs.length === 0) {
        return;
    }

    const gtkCurrent = _gsGtk.get_string('gtk-theme');
    const cinCurrent = _gsCin.get_string('name');

    // Base selection: 'none' resolves the ORIGINAL theme on disk so
    // the clone is rebuilt from the true original (accent detection
    // and selector recoloring use its colors). This walks stacked
    // CLI suffixes (-random, -N, -custom) with existence checks.
    // Other modes keep the fast blind strip: the accent gets
    // overwritten anyway.
    let appBase = '';
    let deskBase = '';
    if (cfg.mode === 'none') {
        appBase = gtkCurrent !== '' ?
            resolveOriginalTheme(gtkCurrent) : '';
        deskBase = cinCurrent !== '' ?
            resolveOriginalTheme(cinCurrent) : '';
    } else {
        appBase = gtkCurrent !== '' ?
            stripTrailingSuffix(gtkCurrent) : '';
        deskBase = cinCurrent !== '' ?
            stripTrailingSuffix(cinCurrent) : '';
    }
    const sameSource = appBase !== '' && appBase === deskBase;

    let resApp = null;
    let resDesk = null;

    if (sameSource) {
        resApp = shiftOneTheme(appBase, cfg);
        resDesk = resApp;
    } else {
        if (appBase !== '') resApp = shiftOneTheme(appBase, cfg);
        if (deskBase !== '') resDesk = shiftOneTheme(deskBase, cfg);
    }

    let appliedDesk = null;
    let appliedApp = null;
    const errors = [];

    if (resApp !== null && resApp.ok) {
        _gsGtk.set_string('gtk-theme', resApp.name);
        appliedApp = resApp.name;
    } else if (resApp !== null) {
        errors.push(resApp.message);
    }
    if (resDesk !== null && resDesk.ok) {
        _gsCin.set_string('name', resDesk.name);
        _gsWm.set_string('theme', resDesk.name);
        appliedDesk = resDesk.name;
    } else if (resDesk !== null && !sameSource) {
        errors.push(resDesk.message);
    }

    if (appliedApp === null && appliedDesk === null) {
        global.logError('[CinnShift] nothing applied: ' +
            errors.join('; '));
        notifyResult(_('CinnShift failed: ') + errors.join('; '));
        return;
    }

    const parts = [];
    if (appliedApp !== null) {
        parts.push(_('Applications=') + appliedApp);
    }
    if (appliedDesk !== null && !sameSource) {
        parts.push(_('Desktop=') + appliedDesk);
    }
    if (errors.length > 0) parts.push(errors.join('; '));

    const accentMsg = cfg.targetAccent !== null ?
        ' Accent=' + cfg.targetAccent : ' Accent=preserved';
    const summary = parts.join(', ') + accentMsg;
    global.log('[CinnShift] applied: ' + summary);
    notifyResult(summary);

    const finalDesk = appliedDesk !== null ?
        appliedDesk : _gsCin.get_string('name');
    const finalApp = appliedApp !== null ?
        appliedApp : _gsGtk.get_string('gtk-theme');
    refreshThemes(finalDesk, finalApp, finalDesk);
}
