/**
 * Blur Template Manager handles blur effect templates
 * Provides predefined blur templates for easy styling
 */
class BlurTemplateManager {
    /**
     * Initialize Blur Template Manager
     * @param {Object} extension - Reference to main extension instance
     */
    constructor(extension) {
        this.extension = extension;
        this.templates = this.initializeTemplates();
    }

    /**
     * Initialize all blur templates
     * @returns {Object} Map of template names to their settings
     */
    initializeTemplates() {
        return {
            // Frosted Glass group
            "frosted-glass": {
                blurRadius: 15,
                blurSaturate: 1.2,
                blurContrast: 1.1,
                blurBrightness: 1.0,
                blurBackground: "rgba(255, 255, 255, 0.2)",
                blurBorderColor: "rgba(255, 255, 255, 0.4)",
                blurBorderWidth: 1,
                blurTransition: 0.5,
                blurOpacity: 0.9,
            },
            "frosted-glass-dark": {
                blurRadius: 22,
                blurSaturate: 0.95,
                blurContrast: 0.75,
                blurBrightness: 0.65,
                blurBackground: "rgba(0, 0, 0, 0.3)",
                blurBorderColor: "rgba(255, 255, 255, 0.15)",
                blurBorderWidth: 1,
                blurTransition: 0.3,
                blurOpacity: 0.8,
            },
            "frosted-glass-orange-light": {
                blurRadius: 18,
                blurSaturate: 1.4,
                blurContrast: 1.2,
                blurBrightness: 1.1,
                blurBackground: "rgba(255, 165, 0, 0.15)",
                blurBorderColor: "rgba(255, 140, 0, 0.3)",
                blurBorderWidth: 1,
                blurTransition: 0.4,
                blurOpacity: 0.88,
            },
            "frosted-glass-orange-dark": {
                blurRadius: 24,
                blurSaturate: 0.9,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(255, 69, 0, 0.2)",
                blurBorderColor: "rgba(255, 140, 0, 0.15)",
                blurBorderWidth: 1,
                blurTransition: 0.5,
                blurOpacity: 0.8,
            },
            "frosted-glass-blue-light": {
                blurRadius: 18,
                blurSaturate: 1.4,
                blurContrast: 1.2,
                blurBrightness: 1.1,
                blurBackground: "rgba(0, 123, 255, 0.15)",
                blurBorderColor: "rgba(0, 86, 179, 0.3)",
                blurBorderWidth: 1,
                blurTransition: 0.4,
                blurOpacity: 0.88,
            },
            "frosted-glass-blue-dark": {
                blurRadius: 24,
                blurSaturate: 0.9,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(0, 51, 160, 0.2)",
                blurBorderColor: "rgba(0, 86, 179, 0.15)",
                blurBorderWidth: 1,
                blurTransition: 0.5,
                blurOpacity: 0.8,
            },
            "frosted-glass-green-light": {
                blurRadius: 18,
                blurSaturate: 1.4,
                blurContrast: 1.2,
                blurBrightness: 1.1,
                blurBackground: "rgba(40, 167, 69, 0.15)",
                blurBorderColor: "rgba(21, 87, 36, 0.3)",
                blurBorderWidth: 1,
                blurTransition: 0.4,
                blurOpacity: 0.88,
            },
            "frosted-glass-green-dark": {
                blurRadius: 24,
                blurSaturate: 0.9,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(21, 87, 36, 0.2)",
                blurBorderColor: "rgba(21, 87, 36, 0.15)",
                blurBorderWidth: 1,
                blurTransition: 0.5,
                blurOpacity: 0.8,
            },
            "frosted-glass-purple-light": {
                blurRadius: 18,
                blurSaturate: 1.4,
                blurContrast: 1.2,
                blurBrightness: 1.1,
                blurBackground: "rgba(102, 51, 153, 0.15)",
                blurBorderColor: "rgba(75, 0, 130, 0.3)",
                blurBorderWidth: 1,
                blurTransition: 0.4,
                blurOpacity: 0.88,
            },
            "frosted-glass-purple-dark": {
                blurRadius: 24,
                blurSaturate: 0.9,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(75, 0, 130, 0.2)",
                blurBorderColor: "rgba(75, 0, 130, 0.15)",
                blurBorderWidth: 1,
                blurTransition: 0.5,
                blurOpacity: 0.8,
            },
            "frosted-glass-red-light": {
                blurRadius: 18,
                blurSaturate: 1.4,
                blurContrast: 1.2,
                blurBrightness: 1.1,
                blurBackground: "rgba(220, 53, 69, 0.15)",
                blurBorderColor: "rgba(176, 42, 55, 0.3)",
                blurBorderWidth: 1,
                blurTransition: 0.4,
                blurOpacity: 0.88,
            },
            "frosted-glass-red-dark": {
                blurRadius: 24,
                blurSaturate: 0.9,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(176, 42, 55, 0.2)",
                blurBorderColor: "rgba(176, 42, 55, 0.15)",
                blurBorderWidth: 1,
                blurTransition: 0.5,
                blurOpacity: 0.8,
            },
            "frosted-glass-pink-light": {
                blurRadius: 18,
                blurSaturate: 1.4,
                blurContrast: 1.2,
                blurBrightness: 1.1,
                blurBackground: "rgba(255, 105, 180, 0.15)",
                blurBorderColor: "rgba(255, 20, 147, 0.3)",
                blurBorderWidth: 1,
                blurTransition: 0.4,
                blurOpacity: 0.88,
            },
            "frosted-glass-pink-dark": {
                blurRadius: 24,
                blurSaturate: 0.9,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(255, 20, 147, 0.2)",
                blurBorderColor: "rgba(255, 20, 147, 0.15)",
                blurBorderWidth: 1,
                blurTransition: 0.5,
                blurOpacity: 0.8,
            },
            // Wet Glass group
            "wet-glass": {
                blurRadius: 25,
                blurSaturate: 1.5,
                blurContrast: 1.2,
                blurBrightness: 1.1,
                blurBackground: "rgba(255, 255, 255, 0.1)",
                blurBorderColor: "rgba(255, 255, 255, 0.2)",
                blurBorderWidth: 2,
                blurTransition: 0.3,
                blurOpacity: 0.8,
            },
            "wet-glass-dark": {
                blurRadius: 28,
                blurSaturate: 0.9,
                blurContrast: 0.7,
                blurBrightness: 0.6,
                blurBackground: "rgba(0, 0, 0, 0.4)",
                blurBorderColor: "rgba(255, 255, 255, 0.1)",
                blurBorderWidth: 2,
                blurTransition: 0.4,
                blurOpacity: 0.7,
            },
            "wet-glass-orange-light": {
                blurRadius: 26,
                blurSaturate: 1.6,
                blurContrast: 1.3,
                blurBrightness: 1.2,
                blurBackground: "rgba(255, 165, 0, 0.1)",
                blurBorderColor: "rgba(255, 140, 0, 0.2)",
                blurBorderWidth: 2,
                blurTransition: 0.3,
                blurOpacity: 0.85,
            },
            "wet-glass-orange-dark": {
                blurRadius: 30,
                blurSaturate: 0.8,
                blurContrast: 0.7,
                blurBrightness: 0.6,
                blurBackground: "rgba(255, 69, 0, 0.4)",
                blurBorderColor: "rgba(255, 140, 0, 0.1)",
                blurBorderWidth: 2,
                blurTransition: 0.4,
                blurOpacity: 0.7,
            },
            "wet-glass-blue-light": {
                blurRadius: 26,
                blurSaturate: 1.6,
                blurContrast: 1.3,
                blurBrightness: 1.2,
                blurBackground: "rgba(0, 123, 255, 0.1)",
                blurBorderColor: "rgba(0, 86, 179, 0.2)",
                blurBorderWidth: 2,
                blurTransition: 0.3,
                blurOpacity: 0.85,
            },
            "wet-glass-blue-dark": {
                blurRadius: 30,
                blurSaturate: 0.8,
                blurContrast: 0.7,
                blurBrightness: 0.6,
                blurBackground: "rgba(0, 51, 160, 0.4)",
                blurBorderColor: "rgba(0, 86, 179, 0.1)",
                blurBorderWidth: 2,
                blurTransition: 0.4,
                blurOpacity: 0.7,
            },
            "wet-glass-green-light": {
                blurRadius: 26,
                blurSaturate: 1.6,
                blurContrast: 1.3,
                blurBrightness: 1.2,
                blurBackground: "rgba(40, 167, 69, 0.1)",
                blurBorderColor: "rgba(21, 87, 36, 0.2)",
                blurBorderWidth: 2,
                blurTransition: 0.3,
                blurOpacity: 0.85,
            },
            "wet-glass-green-dark": {
                blurRadius: 30,
                blurSaturate: 0.8,
                blurContrast: 0.7,
                blurBrightness: 0.6,
                blurBackground: "rgba(21, 87, 36, 0.4)",
                blurBorderColor: "rgba(21, 87, 36, 0.1)",
                blurBorderWidth: 2,
                blurTransition: 0.4,
                blurOpacity: 0.7,
            },
            "wet-glass-purple-light": {
                blurRadius: 26,
                blurSaturate: 1.6,
                blurContrast: 1.3,
                blurBrightness: 1.2,
                blurBackground: "rgba(102, 51, 153, 0.1)",
                blurBorderColor: "rgba(75, 0, 130, 0.2)",
                blurBorderWidth: 2,
                blurTransition: 0.3,
                blurOpacity: 0.85,
            },
            "wet-glass-purple-dark": {
                blurRadius: 30,
                blurSaturate: 0.8,
                blurContrast: 0.7,
                blurBrightness: 0.6,
                blurBackground: "rgba(75, 0, 130, 0.4)",
                blurBorderColor: "rgba(75, 0, 130, 0.1)",
                blurBorderWidth: 2,
                blurTransition: 0.4,
                blurOpacity: 0.7,
            },
            "wet-glass-red-light": {
                blurRadius: 26,
                blurSaturate: 1.6,
                blurContrast: 1.3,
                blurBrightness: 1.2,
                blurBackground: "rgba(220, 53, 69, 0.1)",
                blurBorderColor: "rgba(176, 42, 55, 0.2)",
                blurBorderWidth: 2,
                blurTransition: 0.3,
                blurOpacity: 0.85,
            },
            "wet-glass-red-dark": {
                blurRadius: 30,
                blurSaturate: 0.8,
                blurContrast: 0.7,
                blurBrightness: 0.6,
                blurBackground: "rgba(176, 42, 55, 0.4)",
                blurBorderColor: "rgba(176, 42, 55, 0.1)",
                blurBorderWidth: 2,
                blurTransition: 0.4,
                blurOpacity: 0.7,
            },
            "wet-glass-pink-light": {
                blurRadius: 26,
                blurSaturate: 1.6,
                blurContrast: 1.3,
                blurBrightness: 1.2,
                blurBackground: "rgba(255, 105, 180, 0.1)",
                blurBorderColor: "rgba(255, 20, 147, 0.2)",
                blurBorderWidth: 2,
                blurTransition: 0.3,
                blurOpacity: 0.85,
            },
            "wet-glass-pink-dark": {
                blurRadius: 30,
                blurSaturate: 0.8,
                blurContrast: 0.7,
                blurBrightness: 0.6,
                blurBackground: "rgba(255, 20, 147, 0.4)",
                blurBorderColor: "rgba(255, 20, 147, 0.1)",
                blurBorderWidth: 2,
                blurTransition: 0.4,
                blurOpacity: 0.7,
            },
            // Foggy Glass group
            "foggy-glass": {
                blurRadius: 30,
                blurSaturate: 0.8,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(255, 255, 255, 0.4)",
                blurBorderColor: "rgba(255, 255, 255, 0.3)",
                blurBorderWidth: 1,
                blurTransition: 1.0,
                blurOpacity: 0.7,
            },
            "foggy-glass-dark": {
                blurRadius: 35,
                blurSaturate: 0.7,
                blurContrast: 0.6,
                blurBrightness: 0.5,
                blurBackground: "rgba(0, 0, 0, 0.5)",
                blurBorderColor: "rgba(255, 255, 255, 0.05)",
                blurBorderWidth: 1,
                blurTransition: 1.2,
                blurOpacity: 0.6,
            },
            "foggy-glass-orange-light": {
                blurRadius: 32,
                blurSaturate: 1.0,
                blurContrast: 0.9,
                blurBrightness: 0.8,
                blurBackground: "rgba(255, 165, 0, 0.25)",
                blurBorderColor: "rgba(255, 140, 0, 0.25)",
                blurBorderWidth: 1,
                blurTransition: 0.8,
                blurOpacity: 0.75,
            },
            "foggy-glass-orange-dark": {
                blurRadius: 37,
                blurSaturate: 0.6,
                blurContrast: 0.5,
                blurBrightness: 0.4,
                blurBackground: "rgba(255, 69, 0, 0.4)",
                blurBorderColor: "rgba(255, 140, 0, 0.05)",
                blurBorderWidth: 1,
                blurTransition: 1.0,
                blurOpacity: 0.6,
            },
            "foggy-glass-blue-light": {
                blurRadius: 32,
                blurSaturate: 1.0,
                blurContrast: 0.9,
                blurBrightness: 0.8,
                blurBackground: "rgba(0, 123, 255, 0.25)",
                blurBorderColor: "rgba(0, 86, 179, 0.25)",
                blurBorderWidth: 1,
                blurTransition: 0.8,
                blurOpacity: 0.75,
            },
            "foggy-glass-blue-dark": {
                blurRadius: 37,
                blurSaturate: 0.6,
                blurContrast: 0.5,
                blurBrightness: 0.4,
                blurBackground: "rgba(0, 51, 160, 0.4)",
                blurBorderColor: "rgba(0, 86, 179, 0.05)",
                blurBorderWidth: 1,
                blurTransition: 1.0,
                blurOpacity: 0.6,
            },
            "foggy-glass-green-light": {
                blurRadius: 32,
                blurSaturate: 1.0,
                blurContrast: 0.9,
                blurBrightness: 0.8,
                blurBackground: "rgba(40, 167, 69, 0.25)",
                blurBorderColor: "rgba(21, 87, 36, 0.25)",
                blurBorderWidth: 1,
                blurTransition: 0.8,
                blurOpacity: 0.75,
            },
            "foggy-glass-green-dark": {
                blurRadius: 37,
                blurSaturate: 0.6,
                blurContrast: 0.5,
                blurBrightness: 0.4,
                blurBackground: "rgba(21, 87, 36, 0.4)",
                blurBorderColor: "rgba(21, 87, 36, 0.05)",
                blurBorderWidth: 1,
                blurTransition: 1.0,
                blurOpacity: 0.6,
            },
            "foggy-glass-purple-light": {
                blurRadius: 32,
                blurSaturate: 1.0,
                blurContrast: 0.9,
                blurBrightness: 0.8,
                blurBackground: "rgba(102, 51, 153, 0.25)",
                blurBorderColor: "rgba(75, 0, 130, 0.25)",
                blurBorderWidth: 1,
                blurTransition: 0.8,
                blurOpacity: 0.75,
            },
            "foggy-glass-purple-dark": {
                blurRadius: 37,
                blurSaturate: 0.6,
                blurContrast: 0.5,
                blurBrightness: 0.4,
                blurBackground: "rgba(75, 0, 130, 0.4)",
                blurBorderColor: "rgba(75, 0, 130, 0.05)",
                blurBorderWidth: 1,
                blurTransition: 1.0,
                blurOpacity: 0.6,
            },
            "foggy-glass-red-light": {
                blurRadius: 32,
                blurSaturate: 1.0,
                blurContrast: 0.9,
                blurBrightness: 0.8,
                blurBackground: "rgba(220, 53, 69, 0.25)",
                blurBorderColor: "rgba(176, 42, 55, 0.25)",
                blurBorderWidth: 1,
                blurTransition: 0.8,
                blurOpacity: 0.75,
            },
            "foggy-glass-red-dark": {
                blurRadius: 37,
                blurSaturate: 0.6,
                blurContrast: 0.5,
                blurBrightness: 0.4,
                blurBackground: "rgba(176, 42, 55, 0.4)",
                blurBorderColor: "rgba(176, 42, 55, 0.05)",
                blurBorderWidth: 1,
                blurTransition: 1.0,
                blurOpacity: 0.6,
            },
            "foggy-glass-pink-light": {
                blurRadius: 32,
                blurSaturate: 1.0,
                blurContrast: 0.9,
                blurBrightness: 0.8,
                blurBackground: "rgba(255, 105, 180, 0.25)",
                blurBorderColor: "rgba(255, 20, 147, 0.25)",
                blurBorderWidth: 1,
                blurTransition: 0.8,
                blurOpacity: 0.75,
            },
            "foggy-glass-pink-dark": {
                blurRadius: 37,
                blurSaturate: 0.6,
                blurContrast: 0.5,
                blurBrightness: 0.4,
                blurBackground: "rgba(255, 20, 147, 0.4)",
                blurBorderColor: "rgba(255, 20, 147, 0.05)",
                blurBorderWidth: 1,
                blurTransition: 1.0,
                blurOpacity: 0.6,
            },
            // Clear Crystal group
            "clear-crystal": {
                blurRadius: 10,
                blurSaturate: 1.0,
                blurContrast: 1.0,
                blurBrightness: 1.0,
                blurBackground: "rgba(255, 255, 255, 0.0)",
                blurBorderColor: "rgba(255, 255, 255, 0.5)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 1.0,
            },
            "clear-crystal-dark": {
                blurRadius: 12,
                blurSaturate: 0.9,
                blurContrast: 0.9,
                blurBrightness: 0.8,
                blurBackground: "rgba(0, 0, 0, 0.0)",
                blurBorderColor: "rgba(255, 255, 255, 0.2)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.9,
            },
            "clear-crystal-orange-light": {
                blurRadius: 12,
                blurSaturate: 1.2,
                blurContrast: 1.1,
                blurBrightness: 1.0,
                blurBackground: "rgba(255, 165, 0, 0.0)",
                blurBorderColor: "rgba(255, 140, 0, 0.4)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.95,
            },
            "clear-crystal-orange-dark": {
                blurRadius: 14,
                blurSaturate: 0.8,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(255, 69, 0, 0.0)",
                blurBorderColor: "rgba(255, 140, 0, 0.2)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.9,
            },
            "clear-crystal-blue-light": {
                blurRadius: 12,
                blurSaturate: 1.2,
                blurContrast: 1.1,
                blurBrightness: 1.0,
                blurBackground: "rgba(0, 123, 255, 0.0)",
                blurBorderColor: "rgba(0, 86, 179, 0.4)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.95,
            },
            "clear-crystal-blue-dark": {
                blurRadius: 14,
                blurSaturate: 0.8,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(0, 51, 160, 0.0)",
                blurBorderColor: "rgba(0, 86, 179, 0.2)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.9,
            },
            "clear-crystal-green-light": {
                blurRadius: 12,
                blurSaturate: 1.2,
                blurContrast: 1.1,
                blurBrightness: 1.0,
                blurBackground: "rgba(40, 167, 69, 0.0)",
                blurBorderColor: "rgba(21, 87, 36, 0.4)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.95,
            },
            "clear-crystal-green-dark": {
                blurRadius: 14,
                blurSaturate: 0.8,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(21, 87, 36, 0.0)",
                blurBorderColor: "rgba(21, 87, 36, 0.2)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.9,
            },
            "clear-crystal-purple-light": {
                blurRadius: 12,
                blurSaturate: 1.2,
                blurContrast: 1.1,
                blurBrightness: 1.0,
                blurBackground: "rgba(102, 51, 153, 0.0)",
                blurBorderColor: "rgba(75, 0, 130, 0.4)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.95,
            },
            "clear-crystal-purple-dark": {
                blurRadius: 14,
                blurSaturate: 0.8,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(75, 0, 130, 0.0)",
                blurBorderColor: "rgba(75, 0, 130, 0.2)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.9,
            },
            "clear-crystal-red-light": {
                blurRadius: 12,
                blurSaturate: 1.2,
                blurContrast: 1.1,
                blurBrightness: 1.0,
                blurBackground: "rgba(220, 53, 69, 0.0)",
                blurBorderColor: "rgba(176, 42, 55, 0.4)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.95,
            },
            "clear-crystal-red-dark": {
                blurRadius: 14,
                blurSaturate: 0.8,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(176, 42, 55, 0.0)",
                blurBorderColor: "rgba(176, 42, 55, 0.2)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.9,
            },
            "clear-crystal-pink-light": {
                blurRadius: 12,
                blurSaturate: 1.2,
                blurContrast: 1.1,
                blurBrightness: 1.0,
                blurBackground: "rgba(255, 105, 180, 0.0)",
                blurBorderColor: "rgba(255, 20, 147, 0.4)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.95,
            },
            "clear-crystal-pink-dark": {
                blurRadius: 14,
                blurSaturate: 0.8,
                blurContrast: 0.8,
                blurBrightness: 0.7,
                blurBackground: "rgba(255, 20, 147, 0.0)",
                blurBorderColor: "rgba(255, 20, 147, 0.2)",
                blurBorderWidth: 1,
                blurTransition: 0.2,
                blurOpacity: 0.9,
            },
        };
    }

    /**
     * Apply a template to the extension settings
     * @param {string} templateName - Name of the template to apply
     */
    applyTemplate(templateName) {
        this.extension.debugLog(`Applying blur template: ${templateName}`);

        const selectedTemplate = this.templates[templateName];
        if (!selectedTemplate) {
            this.extension.debugLog(`Invalid template selected: ${templateName}`);
            return;
        }

        try {
            // Apply template values to settings
            Object.keys(selectedTemplate).forEach((key) => {
                const settingKey = key.replace(/([A-Z])/g, "-$1").toLowerCase();
                this.extension.settings.setValue(settingKey, selectedTemplate[key]);
            });

            this.extension.debugLog(`Blur template ${templateName} applied successfully`);

            // Update CSS variables to apply changes immediately
            this.extension.cssManager.updateAllVariables();
            this.extension.transparencyManager.applyPanelStyles();
        } catch (e) {
            this.extension.debugLog("Error applying blur template:", e);
        }
    }

    /**
     * Get list of available templates
     * @returns {Array} Array of template names
     */
    getAvailableTemplates() {
        return Object.keys(this.templates);
    }

    /**
     * Get template configuration
     * @param {string} templateName - Name of the template
     * @returns {Object|null} Template configuration or null if not found
     */
    getTemplate(templateName) {
        return this.templates[templateName] || null;
    }
}

module.exports = BlurTemplateManager;
